### ISSUE TITLE
[TC6 - front-end] Na het inloggen komt de gebruiker op een lege pagina terecht

### ISSUE THREAD

**Issue by DianaDirksen** [kevin-pi/IntegratedTravelWebsite#15]
Reproductie:
Open de website: https://www.phptravels.net/
Klik op   My Account >> Log in
Log   in met username: user@phptravels.com met wachtwoord: demouser.

Verwacht resultaat: De accountpagina wordt geopend.
Werkelijk resultaat: De accountpagina wordt geladen, maar is blanco. Het web-adres moet aangepast worden naar het originele adres om iets te kunnen doen. Bij opnieuw laden van de pagina, is de gebruiker ingelogd.

![image](https://user-images.githubusercontent.com/43573775/46138846-50488380-c24d-11e8-949e-811bb2ff7474.png)

**Comment by kevin-pi** [comment]
Issue fixed in nieuwe versie
