### ISSUE TITLE
[TC2 - front-end] Lay-out van zoekresultaten Hotels is niet correct

### ISSUE THREAD

**Issue by DianaDirksen** [kevin-pi/IntegratedTravelWebsite#6]
Reproductie:
Open de website: https://www.phptravels.net/
Selecteer Hotels.
Voer in: Swissotel Le Plaza Basel, 12-10-2018, 15-10-2018, 1 volwassenen.
Klik op Search.

De lay-out van de results pagina lijkt niet correct te zijn. Zie screenshot.

![image](https://user-images.githubusercontent.com/43573775/46130155-da3a2180-c238-11e8-95f3-502d36cc4906.png)

**Comment by kevin-pi** [comment]
Issue fixed in new version.
