### ISSUE TITLE
[TC2 Front-end] - zoekfunctie naar hotels in een plaats geeft geen resultaten

### ISSUE THREAD

**Issue by DianaDirksen** [kevin-pi/IntegratedTravelWebsite#7]
Reproductie:
Open de website: https://www.phptravels.net/
Selecteer Hotels.
Voer in: London, 30-09-2018, 07-10-2018, 2 volwassenen, 2 kinderen.
Klik op Search.

Verwacht resultaat:  Alle beschikbare hotels in Londen voor die periode worden getoond 
Werkelijk resultaat: Er worden geen hotels getoond. Zie screenshot

![image](https://user-images.githubusercontent.com/43573775/46130294-3ac95e80-c239-11e8-99f8-65fc4fd3efe3.png)

**Comment by kevin-pi** [comment]
Issue fixed in new version. Grand Plaza Apartments in London wordt getoond.
